#!/bin/bash
# KIME Installation Script (auto-generated by Blunux installer)
# Run this if kime was not installed during system installation

set -e

echo "Installing kime-git..."

# Check if yay is installed
if ! command -v yay &> /dev/null; then
    echo "Installing yay first..."
    BUILDDIR=$(mktemp -d)
    git clone https://aur.archlinux.org/yay-bin.git "$BUILDDIR/yay-bin"
    cd "$BUILDDIR/yay-bin"
    makepkg -si --noconfirm
    cd /
    rm -rf "$BUILDDIR"
fi

# Install kime-git
yay -S --noconfirm --needed kime-git

echo "kime-git installed successfully!"
echo "Please log out and log back in for changes to take effect."
